### PR TITLE
Fix incorrect text displayed and date parsing

### LINKED ISSUE #140: [PE-D][Tester E] Incorrect Text
Repetition of text
eg. Phone: Phone..

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: sjoann/ped#1

### LINKED ISSUE #147: [PE-D][Tester E] Inputting a non-existing date
Inputting a non existing date such as 31 Nov 2022 is allowed.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: sjoann/ped#5

### LINKED ISSUE #176: [PE-D][Tester D] Invalid dates should be rejected, instead of being silently adjusted to be the nearest valid date
When adding a past appointment with an invalid date, the earliest valid date gets automatically chosen. This is incorrect behaviour, as it can lead user typos to be accepted. 

For example, the command `appt 6 on/29-02-2022 diag/Common cold, viral flu m/Panadolx m/Lozenges` is incorrect because of Feb 29. As seen in the screenshot, the date get automatically chosen to be 28 Feb without any warning to the user. I only discovered this bug because I meant to type 29 March, but my fat fingers got in the way and I typed `2` instead of `3`.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: parth-io/ped#8

### PR DESCRIPTION
**Pull request by kxrt**
- [Fix text duplication bug on printing person](https://github.com/AY2223S1-CS2103T-W16-3/tp/commit/51e4e76e25803634bc1ec5a1033273acaefbd325) - Fixes #140 
- [Fix incorrect Optional::get calls](https://github.com/AY2223S1-CS2103T-W16-3/tp/commit/a57578d4cf88354902d3fb4b88429258d61ea3ae)
- [Enable stricter parsing to catch non-existent dates](https://github.com/AY2223S1-CS2103T-W16-3/tp/commit/6cd51b25e5b4ab25b736c71cb5dabcf0f94cc5ad) - Fixes #147, Fixes #176
- [Add tests for Appointment::isValidDate changes, update dates to dd-MM-uuuu](https://github.com/AY2223S1-CS2103T-W16-3/tp/commit/9cbf20b5a6ee21523df7e1cbe2611184b6a9fad8)

### CODE REVIEW

File: src/main/java/seedu/address/model/appointment/Appointment.java [hunk 1]
```diff
@@ -8,7 +8,7 @@
  * Represents an appointment for a patient.
  */
 public abstract class Appointment {
-    public static final String DATE_FORMAT = "dd-MM-yyyy";
+    public static final String DATE_FORMAT = "dd-MM-uuuu";
```
Comment (PeiYee88) [inline src/main/java/seedu/address/model/appointment/Appointment.java:11]: I think it may not be a good idea to change `yyyy` to `uuuu` here as this will be the message printed in the result display box and the user will not know what `uuuu` means

File: src/main/java/seedu/address/model/person/Person.java [hunk 2]
```diff
@@ -239,22 +239,22 @@ public int hashCode() {
...
                 .append(getPatientType());
 
         if (getPatientType().isInpatient()) {
-            builder.append("; Hospital Wing: ")
-                    .append(getHospitalWing())
-                    .append("; Floor Number: ")
-                    .append(getFloorNumber())
-                    .append("; Ward Number: ")
-                    .append(getWardNumber());
+            builder.append("; ")
```
Comment (PeiYee88) [inline src/main/java/seedu/address/model/person/Person.java:252]: Thanks for removing the duplicates message

**Review by PeiYee88 — APPROVED** [review]
Minor edits required. Feel free to merge after editing.

File: src/main/java/seedu/address/model/appointment/Appointment.java (hunk 1 above)
Comment (kxrt) [reply src/main/java/seedu/address/model/appointment/Appointment.java]: Fixed!
