### PR TITLE
Fix bug in sample users, add support for no upcoming appointment

### LINKED ISSUE #114: Parsing bug prevents application startup
The string `Wing 1` prevents the application from starting as it is no longer considered a valid Hospital Wing. Swap this for an acceptable input.

### PR DESCRIPTION
**Pull request by kxrt**
The string `Wing 1` in [SampleDataUtil](https://github.com/AY2223S1-CS2103T-W16-3/tp/blob/cde75ec86593dde9a94067b8ed56f969044898b4/src/main/java/seedu/address/model/util/SampleDataUtil.java#L43) prevented the application from starting as it is no longer considered a valid Hospital Wing. This has been swapped for an acceptable input.

The command `edit <INDEX> upcoming/` with no date after `upcoming/` will reset a person's UpcomingAppointment to `None` int the UI.

Fixes #114

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -29,6 +29,7 @@ public static boolean containsWordIgnoreCase(String sentence, String word) {
 
         String preppedWord = word.trim();
         checkArgument(!preppedWord.isEmpty(), "Word parameter cannot be empty");
+        System.out.println(preppedWord);
```
Comment (nehcuy) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: Remember to remove the System.out.println!

**Review by nehcuy — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/commons/util/StringUtil.java (hunk 1 above)
Comment (kxrt) [reply src/main/java/seedu/address/commons/util/StringUtil.java]: Whoops, done!
