### PR TITLE
Update medication map, fix updating of census on patient deletion

### LINKED ISSUE #97: Update count census when patients are deleted from the database
Currently, count census only increases on patient creation, and remains the same when patients are deleted.

### LINKED ISSUE #98: Update count census when PastAppointments are created
Currently, count census only increases on patient creation, and remains the same when `PastAppointment`s are created.

### PR DESCRIPTION
**Pull request by kxrt**
The map persisted whenever new AddressBook objects were
initialised and this led to inconsistencies from certain commands.

Hence.
- Refactor static map object into MedicationMap.java
- Update dependencies to use new class
- Update relevant test cases

Fixes #97, fixes #98

### CODE REVIEW

File: src/main/java/seedu/address/model/tag/MedicationMap.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+        person.getMedications().forEach(this::add);
+    }
+
+    /**
+     * Clears the medication map of medications allocated to the patient.
+     * @param patient The patient to be removed.
+     */
+    public void clearMedicationsOfPatient(Person patient) {
+        patient.getMedications().forEach(this::remove);
+    }
```
Comment (nehcuy) [inline src/main/java/seedu/address/model/tag/MedicationMap.java:53]: Just a slight change, I believe it's better to use the same parameter name for both `MedicationMap::addMedicationsOfPatient` and `MedicationMap::clearMedicationsOfPatient`.

Either use `Person person` or `Person patient` for both.

File: src/main/java/seedu/address/model/tag/MedicationMap.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+
+    public String getMedicationMapSimplified() {
+        StringBuilder sb = new StringBuilder();
+        medicationMap.keySet().stream().sorted()
+                .forEach(medication ->
+                        sb.append(medication)
+                                .append(" /-/-/ ")
+                                .append(medicationMap.get(medication))
+                                .append(" /-/-/ "));
```
Comment (nehcuy) [inline src/main/java/seedu/address/model/tag/MedicationMap.java:86]: It would be better to either add the spacer used between medications as a constant in the class to prevent "magic literals". You could also perhaps put a small comment beside the `.append(" /-/-/ ")` saying that it is an internal spacer used only for the `Medication` class.

File: src/main/java/seedu/address/model/AddressBook.java [hunk 3]
```diff
@@ -56,6 +60,11 @@ public void resetData(ReadOnlyAddressBook newData) {
         requireNonNull(newData);
 
         setPersons(newData.getPersonList());
+        setMedicationMap(newData.getMedicationMapObject());
+    }
+
+    private void setMedicationMap(String medicationMap) {
+        this.medicationMap.setMedicationMap(medicationMap);
```
Comment (nehcuy) [inline src/main/java/seedu/address/model/AddressBook.java:67]: This might be confused with recursion on first glance, but I understand the two methods are from different classes. Perhaps renaming `setMedicationMap` in
```java
 this.medicationMap.setMedicationMap(medicationMap);
```
would be a better option.

**Review by nehcuy — CHANGES_REQUESTED** [review]
I think it's good to go after making the appropriate changes! Please let me know if you agree with the changes requested. Thanks!

File: src/main/java/seedu/address/model/tag/MedicationMap.java (hunk 2 above)
Comment (kxrt) [reply src/main/java/seedu/address/model/tag/MedicationMap.java]: That's fair. Changed this in the latest commit.

File: src/main/java/seedu/address/model/AddressBook.java (hunk 3 above)
Comment (kxrt) [reply src/main/java/seedu/address/model/AddressBook.java]: Fair enough. I've renamed them to imply the usage of stringified versions of the map.

**Review by nehcuy — APPROVED** [review]
Thanks for the change! LGTM. :>
